### PR TITLE
feat: add media partners

### PR DESCRIPTION
**Pull request by anyulled**

### CODE REVIEW

**Review by icougil — CHANGES_REQUESTED** [review]
MP images are really really small (at least in IMHO in a 14'' screen)...

**Comment by icougil** [comment]
regarding [my last comment](https://github.com/dev-bcn/dev-bcn.github.io/pull/62#issuecomment-1431771180), @anyulled is there anything we can do in order to "highlight" any Sponsor once we are "overing" each image (one by one) ? 
Could be an improvement of course, I think we can merge this PR, but I'd like to know if we can do something easily in order to make it happen if it's possible now (that we will have 2 sponsors in 1 type)

**Review by icougil — COMMENTED** [review]
see my last comment: https://github.com/dev-bcn/dev-bcn.github.io/pull/62#issuecomment-1437592762

**Comment by anyulled** [comment]
> regarding [my last comment](https://github.com/dev-bcn/dev-bcn.github.io/pull/62#issuecomment-1431771180), @anyulled is there anything we can do in order to "highlight" any Sponsor once we are "overing" each image (one by one) ? 
> Could be an improvement of course, I think we can merge this PR, but I'd like to know if we can do something easily in order to make it happen if it's possible now (that we will have 2 sponsors in 1 type)

Yes, we can apply an individual effect when hovering over an image, but I need to merge these two pull requests to avoid duplicating the work or copy pasting.

**Comment by icougil** [comment]
then for me it is ok 👍

**Review by icougil — APPROVED** [review]

**Comment by jonathanvila** [comment]
I'm not sure that the shadow is ok with these logos, in some cases makes harder to read them

image

**Pull request merged**
