### PR TITLE
feat: add Premium and regular sponsors

### PR DESCRIPTION
**Pull request by anyulled**
Add the following sponsors

1. Barcelona JUG as Premium
2. Adaptive as Regular

### CODE REVIEW

**Comment by icougil** [comment]
Also why the preview is not working?

**Comment by anyulled** [comment]
Ok.

The preview isn't working because I set any compilation warning as a
failure.

I will resolve it and push more changes today

**Comment by jonathanvila** [comment]
My review:
1. logos don't have their size depending on the level....both are the same size and it should not be 
2. the top menu SPONSORS is missing
3. barcelonajug link should point to meetup, the blogger website has not been updated in more than 2 years

**Review by jonathanvila — CHANGES_REQUESTED** [review]
My review:

1. logos don't have their size depending on the level....both are the same size and it should not be
2. the top menu SPONSORS is missing
3. barcelonajug link should point to meetup, the blogger website has not been updated in more than 2 years

**Comment by anyulled** [comment]
> My review:
> 
> 1. logos don't have their size depending on the level....both are the same size and it should not be
> 2. the top menu SPONSORS is missing
> 3. barcelonajug link should point to meetup, the blogger website has not been updated in more than 2 years

Ok, I'll work on those points. Top and other sponsorship levels are not displayed because there are no sponsors in that category yet. Do you want them to appear empty instead?

**Comment by anyulled** [comment]
**Premium sponsor image height:** 118.5 px
image

**Regular sponsor image height:** 66.5 px
image

Current proportion is twice the size. How bigger should be the different between categories?

For the JBCNConf the relationship is the same:
* Top: 250px
* Premium: 150px
* Regular: 71px

**Comment by jonathanvila** [comment]
> . Top and other sponsorship levels are not displayed because there are no sponsors in that category yet. Do you want them to appear empty instead?

What I mean by the "top menu Sponsors is missing" is the Menu option "Sponsors" in the web site top menu
image

**Comment by jonathanvila** [comment]
> Current proportion is twice the size. How bigger should be the different between categories?
In order to see it better, can you add Adaptive as Premium and the Jug as Regular ? in the image you posted I see that what is double is the height, but at least for me with theses logos it's no so clear one in way bigger than the other.

**Comment by anyulled** [comment]
> > Current proportion is twice the size. How bigger should be the different between categories?
> 
> In order to see it better, can you add Adaptive as Premium and the Jug as Regular, too, apart of what you already have ? in the image you posted I see that what is double is the height, but at least for me with theses logos it's no so clear one in way bigger than the other.

This is how they both look as regular sponsors.

image

**Comment by anyulled** [comment]
> > Current proportion is twice the size. How bigger should be the different between categories?
> 
> In order to see it better, can you add Adaptive as Premium and the Jug as Regular, too, apart of what you already have ? in the image you posted I see that what is double is the height, but at least for me with theses logos it's no so clear one in way bigger than the other.

This is how they see compared in each category

image

**Comment by icougil** [comment]
For me looks good, but at the same time, remember that we should have different anchors for different types of Sponsors. I'm talking on something like:
```
#premium-sponsors
#regular-sponsors
etc...
```

**Comment by anyulled** [comment]
Ok, good. Tonight I'll add those too

**Comment by anyulled** [comment]
> One question that I have is, how will look like if we have 10 of each? like this?

They will be horizontally distributed, and they will have more vertical space between them.

**Pull request merged**
