### PR TITLE
feat: include schedule section

### PR DESCRIPTION
**Pull request by anyulled**
Include the schedule section.

### CODE REVIEW

**Review by icougil — CHANGES_REQUESTED** [review]
I can't read the contents of the keynotes with the actual colors.

But, by adding the background color `"#8ec9ee"` for the `#.sz-session--service .sz-session__card` style it looks much better (IMHO). Like this:
image

Now I can see that the keynotes, breaks, lunch, etc had the "Java" tag associated, and they should not have any associated.

Also, the sessions when we have lighting talks and/or another type of session looks not so well:
image

Can be possible to show this in another way? I don't know, the lighting talks for example with another colours or with smaller boxes? (I'm sure people will not notice the # of minutes per session...)

**Comment by anyulled** [comment]
> 

I applied the color changes you requested and will forward your comments to the sessionize team, as this is a styled html format directly from their API.

**Comment by anyulled** [comment]
> I can't read the contents of the keynotes with the actual colors.
> 
> But, by adding the background color `"#8ec9ee"` for the `#.sz-session--service .sz-session__card` style it looks much better (IMHO). Like this: image
> 
> Now I can see that the keynotes, breaks, lunch, etc had the "Java" tag associated, and they should not have any associated.
> 
> Also, the sessions when we have lighting talks and/or another type of session looks not so well: image
> 
> Can be possible to show this in another way? I don't know, the lighting talks for example with another colours or with smaller boxes? (I'm sure people will not notice the # of minutes per session...)

They told me two things:

1. We can create more rooms and have those sessions there. The thing is they will now appear more tracks in the schedule.
2. We can apply proportional heights to sessions and looks more uniform, but I noticed that it also displays a blank space for the 15 minutes break between session.

image

Shall I create more plenum sessions between talks?

**Comment by icougil** [comment]
can we get rid of the "Java" keyword in the talks that are not related with Java?

image

**Comment by icougil** [comment]
Can't see the _"Coffee break"_ here 😅
image

On the other hand, we should not include _"Session break"_ when sessions are following each other, like in this case:
image
Sessions should appear really close to the next/previous one

On Tuesday I think the times/sizes are not correct (at least for the coffee break):
image

Btw, I think there is something wrong with the identification of the sessions: 

We can see there is some session that belongs to another track. For example _"Gentle Introduction to eBPF"_ from _Ayesha Kaleem_ belongs to the _Devops_ track, not to _Native_ (we have it already like this in our website)
image
Can you check if the assignments are correct?

Lastly, can we try to have 1 slot for all the lightning talks?

**Comment by anyulled** [comment]
Yes, I'm still doing changes here. I added more tracks on the sessionize
schedule and this updated the html, so I need to apply the css rules again.

Regarding the session break, it's for filling the 15 minutes blank space
between talks.

And about the talks track classification, I was told that there are not
enough native language talks and we need to cover that space with talks
from other tracks.

I'll resume working with the CSS today, now that the track structure is
updated and request your feedback.

**Comment by icougil** [comment]
> Yes, I'm still doing changes here. I added more tracks on the sessionize schedule and this updated the html, so I need to apply the css rules again. 
👍
> Regarding the session break, it's for filling the 15 minutes blank space between talks. 
ok, I would suggest making the space smaller (if possible), in the end it is only the time needed for attendees to change rooms.

> And about the talks track classification, I was told that there are not enough native language talks and we need to cover that space with talks from other tracks. 
yes, that's true, what we have to do is, based on our Excel change the corresponding sessions to appear in the Native ones

> I'll resume working with the CSS today, now that the track structure is updated and request your feedback. 
👍

**Review by icougil — APPROVED** [review]

**Pull request merged**
