### PR TITLE
feat: add filter on talks page

### LINKED ISSUE #109: remove button on talks page
Replace the button with a link to the talk

### LINKED ISSUE #110: Allow filtering by track on the talks page
Include a way to filter out talks by the track they belong to.

### PR DESCRIPTION
**Pull request by anyulled**
Closes #109 
closes #110

### Additional requests

- [x] The font size in the combo is small (compared with the rest of the elements of the page) and I can't see them properly (could we need a shadow, underline?)

- [x] It could be great to identify the type of each talk (if it's a talk, lighting talk or a workshop)

- [x] It does not maintain the filter if you go to a talk, and then you go back, can we do something to maintain it?

- [x] It will be nice if we could have an anchor for each track (nice to have, not mandatory)

- [x] could be that we are missing some keywords to add more colour to many tags? (ex: Java, serverless, GraalVM, performance, profile, refactor, tools, security, Quarkus, practices, refactor, ml, frontend, react, Redux, etc)

- [x]  we don't need the “Format” and “Level” prefix, we can remove it and also use some emojis in order to make them clearly visible. For example:
- workshops → 💻
- talks → 🗣️
- lighting talks → ⚡
- and use something like ⭐ to indicate the level of expertise.

- [x] Also, the font for that can be slightly smaller (0.8em).

### CODE REVIEW

**Comment by icougil** [comment]
I think it can be improved with few things:
- The font size in the combo are small (compared with the rest of the elements of the page) and I can't see them properly (could we need a shadow, underline or something?) 
image

- It could be great to identify the type of each talk (if it's a talk, lighting talk or a workshop)
- It does not maintain the filter if you go to a talk and then you go back, can we do something to maintain it?
- It will be nice if we could have an anchor for each track (nice to have, not mandatory)
- could be that we are missing some keywords to add more colour to many tags? (ex: Java, serverless, GraalVM, performance, profil, refactor, tools, security, quarkus, practices, refactor, ml, frontend, react, redux, etc) 
image

**Review by icougil — COMMENTED** [review]
Comment added...

**Comment by anyulled** [comment]
Oh, That's a scope change! I'll work on that.

- [ ] The font size in the combo is small (compared with the rest of the elements of the page) and I can't see them properly (could we need a shadow, underline?)

- [ ] It could be great to identify the type of each talk (if it's a talk, lighting talk or a workshop)

- [x] It does not maintain the filter if you go to a talk, and then you go back, can we do something to maintain it?

- [x] It will be nice if we could have an anchor for each track (nice to have, not mandatory)

- [ ] could be that we are missing some keywords to add more colour to many tags? (ex: Java, serverless, GraalVM, performance, profile, refactor, tools, security, Quarkus, practices, refactor, ml, frontend, react, Redux, etc)

**Comment by icougil** [comment]
Looks much better now 👌

Btw, I was thinking that we don't need the "Format" and "Level" prefix, we can remove it and also use some emojis in order to make them clearly visible. For example

-  workshops -> 💻  
- talks -> 🗣️ 
- lighting talks -> ⚡ 
- and use something like ⭐ to indicate the level of expertise
Also the font for that can be slightly smaller (_0.8em_). 

It will be look like:
image

WDYT?

**Review by icougil — APPROVED** [review]
👍👌

**Pull request merged**
