### PR TITLE
feat: include CaixaBank as BASIC sponsor

### PR DESCRIPTION
**Pull request by anyulled**
include CaixaBank as BASIC sponsor

### CODE REVIEW

**Comment by icougil** [comment]
I think we should remove the box around the logo, as it is the Adaptive one, otherwise the shadow will not be the same. It is done in purpose? Ah! could be because the Adaptive one is transparent? Should we do the same with the CaixaBank one and then have the same behaviour?
image

**Review by icougil — COMMENTED** [review]
see my last comment: https://github.com/dev-bcn/dev-bcn.github.io/pull/64#issuecomment-1437598311

**Comment by anyulled** [comment]
> I think we should remove the box around the logo, as it is the Adaptive one, otherwise the shadow will not be the same. It is done in purpose? Ah! could be because the Adaptive one is transparent? Should we do the same with the CaixaBank one and then have the same behaviour?
> image
> 
> 

It happens because the image format, the adaptive logo is transparent and the other one has white background. Are you suggesting me to modify the logo to remove the background? Or should we request another logo to the sponsor?

**Comment by icougil** [comment]
if we don't remove the background, then we need to add extra space to the logo of the sponsor, otherwise the box is really really close to the actual limits of the image...
it could be a matter of adding a border (changing the logo or via CSS if it's possible,... but I'm not sure if it will  happen to all the logos)...

**Comment by anyulled** [comment]
> if we don't remove the background, then we need to add extra space to the logo of the sponsor, otherwise the box is really really close to the actual limits of the image...
> it could be a matter of adding a border (changing the logo or via CSS if it's possible,... but I'm not sure if it will  happen to all the logos)...

Ok, I'll modify the sponsor image and increase the extra space outside of the logo. I could add more padding with css, but it'll be applied to all the images in that category. The first approach is better

**Review by jonathanvila — APPROVED** [review]
LGTM

**Pull request merged**
