### PR TITLE
fix: add not found route

### PR DESCRIPTION
**Pull request by anyulled**
Adding error reporting & and a not found route to render a not fond component

### CODE REVIEW

**Review by jonathanvila — APPROVED** [review]
LGTM

**Comment by icougil** [comment]
It is this solved? I tried a URL that wasn't exists and I can repeat the same problem...

**Comment by anyulled** [comment]
It's not deployed yet. I'll wait until this afternoon, after al social media posts are published.

**Comment by anyulled** [comment]
Deployed 
image

**Pull request merged**
