### PR TITLE
feat: resize sponsorship carrousel

### PR DESCRIPTION
**Pull request by anyulled**
solves #578

### CODE REVIEW

**Comment by icougil** [comment]
Few things I found:
- I think the sponsorship button is still opening a new tab always image
- The link always points to www.devbcn.com/sponsorship (I guess it should be relative to where are we)?
- Lastly, couldn't we use some pictures from the last year?
(the sizing of the images look much better now to me 👌)

**Review by icougil — CHANGES_REQUESTED** [review]
See my last comment

**Review by jonathanvila — CHANGES_REQUESTED** [review]
A mi me sale que el < de la izquierda se come el texto.... no se si soy solo yo
Screenshot 2024-11-14 at 09 45 45

**Comment by icougil** [comment]
> A mi me sale que el < de la izquierda se come el texto.... no se si soy solo yo 

Sí, yo lo veo tb así

**Comment by anyulled** [comment]
> * The link always points to [www.devbcn.com/sponsorship](http://www.devbcn.com/sponsorship) (I guess it should be relative to where are we)?

Do you want to have a different sponsorship page per edition? What if the sponsor opens an old brochure and gets confused about the pricing and package options?

**Comment by anyulled** [comment]
> A mi me sale que el < de la izquierda se come el texto.... no se si soy solo yo Screenshot 2024-11-14 at 09 45 45

Fixed

**Comment by icougil** [comment]
> > * The link always points to [www.devbcn.com/sponsorship](http://www.devbcn.com/sponsorship) (I guess it should be relative to where are we)?
> 
> Do you want to have a different sponsorship page per edition? What if the sponsor opens an old brochure and gets confused about the pricing and package options?

I mean, the issue is that I was having a look at the preview via Netifly and the link was going to the "live" website (_production_), not to the "corresponding version" that was built.

And ye, I think we should have different Sponsorship pages per edition (at least in each page things that are different: year, dates, etc)
image
image

And the brochure will be always different...

**Review by jonathanvila — APPROVED** [review]
LGTM :)

**Review by icougil — APPROVED** [review]

**Pull request merged**
