### PR TITLE
feat: get speakers from sessionize API

### PR DESCRIPTION
**Pull request by anyulled**
Get approved and confirmed speakers from sessionize API. As there are still some confirmed speakers without a session, I'll leave them hard-coded and will remove them as soon as they have a confirmed session.

### CODE REVIEW

**Comment by icougil** [comment]
With the actual approach we can't see the Talk name in the main page with the speakers... 
image
Can we do something around it?

About Talks, I guess we will have different pages for each Track? Otherwise I don't know how all the talks will appear here,.. like more rows and columns?
image

**Comment by anyulled** [comment]
> Can we do something around it?

Yes, I can display session name when retrieving the list of speakers, but there are still some speakers without a confirmed session. I'll make the change today.

**Comment by anyulled** [comment]
> About Talks, I guess we will have different pages for each Track? Otherwise I don't know how all the talks will appear here,.. like more rows and columns?

I was thinking of having all the talks on the same page, the same way as we had in the [past](https://www.jbcnconf.com/2022/talks.html). But this time I'm adding the track name, and using a grid instead of a list for saving space.

I can include a dropdown in the future to filter the talks by track.

**Comment by anyulled** [comment]
> Btw, will we have a Speakers page where we can see all the speakers but without being included in the main page?

I'm uncertain if I understand. On the main page, we will only have a small selection of 10 – 15 speakers. On the speaker page, we will have all the approved speakers from the API.

**Comment by icougil** [comment]
> 

Got it! Then I guess all the talks will fit in the "Talks page", nice! 👍

**Review by icougil — APPROVED** [review]

**Pull request merged**
