### PR TITLE
feat: include session feedback section

### PR DESCRIPTION
**Pull request by anyulled**
Include session feedback section

https://deploy-preview-225--dev-bcn.netlify.app/session

### CODE REVIEW

**Comment by icougil** [comment]
There are a lot that are empty, not sure if worth to add them... and the other point is that with this way it will not be possible to see the amount of votes for each session (not sure if it's important).

Could be much better if you make the title without a background?
image

WDYT?

**Comment by anyulled** [comment]
> There are a lot that are empty, not sure if worth to add them... and the other point is that with this way it will not be possible to see the amount of votes for each session (not sure if it's important).
> 
> Could be much better if you make the title without a background? image
> 
> WDYT?

Regarding the empty categories, yes, I can remove them. I didn't include the votes because there were sessions with a vote and sessions with 47 votes, but I can show them too, there was a lack of space and decided to prioritize other data.

About the background, this is a theme I used from the UI framework, I'll see if there's another one with a light background.

**Comment by icougil** [comment]
got, it, makes no sense then to add the # of votes and yes, probably makes sense to not add the ones without any feedback...

**Comment by jonathanvila** [comment]
I think that it would be better to include those without votes, saying no
votes, I mean to avoid the confusion for speakers not seeing their talk in
the list and immediately asking us why their talk is not there

**Comment by anyulled** [comment]
I added the votes column and removed those columns without values.

**Review by icougil — APPROVED** [review]

**Comment by icougil** [comment]
I was thinking... should we add a link .... to see this page somewhere? People will not find it otherwise...

**Comment by anyulled** [comment]
Yes, I will add it the menu.

**Pull request merged**
