### PR TITLE
Feat: include speaker's slideshow in front page

### LINKED ISSUE #17: Create a photo slideshow
Include a slideshow with pictures from the last JBCNConf edition in the home page

### PR DESCRIPTION
**Pull request by anyulled**
closes #17

### CODE REVIEW

**Comment by icougil** [comment]
For me looks good, but at the same time. It is only for me that it is not scrolling smooth down? 
(for me is working fine for example if I click on the Sponsor one)

**Review by icougil — COMMENTED** [review]
see my last comment: https://github.com/dev-bcn/dev-bcn.github.io/pull/63#issuecomment-1437594852

**Comment by anyulled** [comment]
> For me looks good, but at the same time. It is only for me that it is not scrolling smooth down? 
> (for me is working fine for example if I click on the Sponsor one)

I will check

**Comment by jonathanvila** [comment]
Looks good, but if we have 90 speakers, is it going to download all images at once and then it simply iterates over them visually ? is this going to make the loading time to be way longer ?

**Comment by anyulled** [comment]
> Looks good, but if we have 90 speakers, is it going to download all images at once and then it simply iterates over them visually ? is this going to make the loading time to be way longer ?

It's taking the speakers from the hard-coded file. Whenever we do the integration with the sessionize API, I'll collect a smaller sample of random speakers and lazy load the images, to avoid impacting the first render of the page.

**Pull request merged**
