### PR TITLE
Feat/assistant information

### PR DESCRIPTION
**Pull request by anyulled**

### CODE REVIEW

**Review by icougil — CHANGES_REQUESTED** [review]
I'd suggest to include the Azul logo a bit smaller (it is immense in big screens)
I'll be more clear on how attendees can attend and grab a ticket for attending the party
I'll be more clear as well (bold letter?) to share which email the users MUST use in order to have proper access to the mobile app
Btw, where in the menu will this appear? Will we create a new "News" section and then later 1 for Speakers other for Attendees, etc or how?

**Comment by icougil** [comment]
Can you see correctly the menu in a not-so-big screen? (not in my case...)
image

Could we include some "other sections" in there? For example the _"CFP-comittee"_? (a lot of chars) and/or the _"Diversity"_ ?
WDYT?

**Review by icougil — COMMENTED** [review]
see last comment

**Comment by anyulled** [comment]
> Could we include some "other sections" in there? For example the _"CFP-comittee"_? (a lot of chars) and/or the _"Diversity"_ ? WDYT?

Another menu, you mean? I was considering removing that link from the top menu and adding it to the **about us** section.

**Comment by icougil** [comment]
> > Could we include some "other sections" in there? For example the _"CFP-comittee"_? (a lot of chars) and/or the _"Diversity"_ ? WDYT?
> 
> Another menu, you mean? I was considering removing that link from the top menu and adding it to the **about us** section.

No, no, just moving the sections I mentioned to be included in this new "news" menu option. But yes another "main menu section" like _"About us"_ will also work if we can move there what we have right now in the _"About us"_ + _"CFP-comittee"_ and also move the _"Diversity"_ into the "news" one

**Review by icougil — APPROVED** [review]

**Pull request merged**
