### PR TITLE
feat: include diversity section

### PR DESCRIPTION
**Pull request by anyulled**
As the sponsors aren't still confirmed, I'm using their images from the official web and their media Kit.

### CODE REVIEW

**Review by icougil — COMMENTED** [review]
For me it will be ready to merge once we have the confirmation from each company.

PS: Can we add a link from their logos to their respective websites? It will be very handy (I think, everybody clicks on images) ;-)

**Comment by anyulled** [comment]
Sure! I'll do it tonight

**Comment by icougil** [comment]
can we make the images smaller? 😅
image

**Comment by anyulled** [comment]
> can we make the images smaller? 😅 and also centered ? image

Done.

**Comment by icougil** [comment]
What we are missing here are the conditions (see the next link) + the form (we can create a similar one we used in the past):

https://github.com/barcelonajug/jbcnconf_web/blob/main/2022/_includes/diversity/diversity-terms.html

**Review by icougil — APPROVED** [review]

**Review by icougil — APPROVED** [review]

**Pull request merged**
